/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import { expect, test } from "vitest";
import { buildConfig } from "./config";

const config = buildConfig();

test("All Radix UI colors are transformed", () => {
  const radixColorNames = [
    "gray",
    "graya",
    "grayp3",
    "grayp3a",
    "graydark",
    "graydarka",
    "graydarkp3",
    "graydarkp3a",
    "mauve",
    "mauvea",
    "mauvep3",
    "mauvep3a",
    "mauvedark",
    "mauvedarka",
    "mauvedarkp3",
    "mauvedarkp3a",
    "slate",
    "slatea",
    "slatep3",
    "slatep3a",
    "slatedark",
    "slatedarka",
    "slatedarkp3",
    "slatedarkp3a",
    "sage",
    "sagea",
    "sagep3",
    "sagep3a",
    "sagedark",
    "sagedarka",
    "sagedarkp3",
    "sagedarkp3a",
    "olive",
    "olivea",
    "olivep3",
    "olivep3a",
    "olivedark",
    "olivedarka",
    "olivedarkp3",
    "olivedarkp3a",
    "sand",
    "sanda",
    "sandp3",
    "sandp3a",
    "sanddark",
    "sanddarka",
    "sanddarkp3",
    "sanddarkp3a",
    "gold",
    "golda",
    "goldp3",
    "goldp3a",
    "golddark",
    "golddarka",
    "golddarkp3",
    "golddarkp3a",
    "bronze",
    "bronzea",
    "bronzep3",
    "bronzep3a",
    "bronzedark",
    "bronzedarka",
    "bronzedarkp3",
    "bronzedarkp3a",
    "brown",
    "browna",
    "brownp3",
    "brownp3a",
    "browndark",
    "browndarka",
    "browndarkp3",
    "browndarkp3a",
    "yellow",
    "yellowa",
    "yellowp3",
    "yellowp3a",
    "yellowdark",
    "yellowdarka",
    "yellowdarkp3",
    "yellowdarkp3a",
    "amber",
    "ambera",
    "amberp3",
    "amberp3a",
    "amberdark",
    "amberdarka",
    "amberdarkp3",
    "amberdarkp3a",
    "orange",
    "orangea",
    "orangep3",
    "orangep3a",
    "orangedark",
    "orangedarka",
    "orangedarkp3",
    "orangedarkp3a",
    "tomato",
    "tomatoa",
    "tomatop3",
    "tomatop3a",
    "tomatodark",
    "tomatodarka",
    "tomatodarkp3",
    "tomatodarkp3a",
    "red",
    "reda",
    "redp3",
    "redp3a",
    "reddark",
    "reddarka",
    "reddarkp3",
    "reddarkp3a",
    "ruby",
    "rubya",
    "rubyp3",
    "rubyp3a",
    "rubydark",
    "rubydarka",
    "rubydarkp3",
    "rubydarkp3a",
    "crimson",
    "crimsona",
    "crimsonp3",
    "crimsonp3a",
    "crimsondark",
    "crimsondarka",
    "crimsondarkp3",
    "crimsondarkp3a",
    "pink",
    "pinka",
    "pinkp3",
    "pinkp3a",
    "pinkdark",
    "pinkdarka",
    "pinkdarkp3",
    "pinkdarkp3a",
    "plum",
    "pluma",
    "plump3",
    "plump3a",
    "plumdark",
    "plumdarka",
    "plumdarkp3",
    "plumdarkp3a",
    "purple",
    "purplea",
    "purplep3",
    "purplep3a",
    "purpledark",
    "purpledarka",
    "purpledarkp3",
    "purpledarkp3a",
    "violet",
    "violeta",
    "violetp3",
    "violetp3a",
    "violetdark",
    "violetdarka",
    "violetdarkp3",
    "violetdarkp3a",
    "iris",
    "irisa",
    "irisp3",
    "irisp3a",
    "irisdark",
    "irisdarka",
    "irisdarkp3",
    "irisdarkp3a",
    "indigo",
    "indigoa",
    "indigop3",
    "indigop3a",
    "indigodark",
    "indigodarka",
    "indigodarkp3",
    "indigodarkp3a",
    "blue",
    "bluea",
    "bluep3",
    "bluep3a",
    "bluedark",
    "bluedarka",
    "bluedarkp3",
    "bluedarkp3a",
    "cyan",
    "cyana",
    "cyanp3",
    "cyanp3a",
    "cyandark",
    "cyandarka",
    "cyandarkp3",
    "cyandarkp3a",
    "teal",
    "teala",
    "tealp3",
    "tealp3a",
    "tealdark",
    "tealdarka",
    "tealdarkp3",
    "tealdarkp3a",
    "jade",
    "jadea",
    "jadep3",
    "jadep3a",
    "jadedark",
    "jadedarka",
    "jadedarkp3",
    "jadedarkp3a",
    "green",
    "greena",
    "greenp3",
    "greenp3a",
    "greendark",
    "greendarka",
    "greendarkp3",
    "greendarkp3a",
    "grass",
    "grassa",
    "grassp3",
    "grassp3a",
    "grassdark",
    "grassdarka",
    "grassdarkp3",
    "grassdarkp3a",
    "lime",
    "limea",
    "limep3",
    "limep3a",
    "limedark",
    "limedarka",
    "limedarkp3",
    "limedarkp3a",
    "mint",
    "minta",
    "mintp3",
    "mintp3a",
    "mintdark",
    "mintdarka",
    "mintdarkp3",
    "mintdarkp3a",
    "sky",
    "skya",
    "skyp3",
    "skyp3a",
    "skydark",
    "skydarka",
    "skydarkp3",
    "skydarkp3a",
    "blacka",
    "blackp3a",
    "whitea",
    "whitep3a",
  ];

  for (const colorName of radixColorNames) {
    expect(config.theme.colors).toHaveProperty(colorName, {
      "1": expect.any(String),
      "2": expect.any(String),
      "3": expect.any(String),
      "4": expect.any(String),
      "5": expect.any(String),
      "6": expect.any(String),
      "7": expect.any(String),
      "8": expect.any(String),
      "9": expect.any(String),
      "10": expect.any(String),
      "11": expect.any(String),
      "12": expect.any(String),
    });
  }
});

test("`transparent` and `currentColor` are included", () => {
  expect(config.theme.colors).toHaveProperty("transparent", "transparent");
  expect(config.theme.colors).toHaveProperty("current", "currentColor");
});

test("`black` and `white` are included", () => {
  expect(config.theme.colors).toHaveProperty("black", "black");
  expect(config.theme.colors).toHaveProperty("white", "white");
});
